name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Turbo Bob
      run: curl --fail --location --output bob https://dl.bintray.com/function61/dl/turbobob/20200617_1743_510a0529/bob_linux-amd64 && chmod +x bob
    - name: Build with Turbo Bob
      run: CI_REVISION_ID="$GITHUB_SHA" ./bob build --publish-artefacts
      env:
        DOCKER_CREDS: ${{ secrets.DOCKER_CREDS }}
